//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityNode1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Block
    {
        public int Id { get; set; }
        public string PreviousHash { get; set; }
        public string Hash { get; set; }
        public Nullable<int> IdTicket { get; set; }
    }
}
